
# spring.config.import=optional:config/secrets.properties
spring.application.name=immoNet

# find by mysql spring boot driver class research

# database properties
# ==================================================================================
spring.datasource.url= jdbc:mysql://localhost:3306/immonet_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA /HIbernate properties
# ===================================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.user.name=admin
spring.security.user.password=admin

# Server properties
# ===================================================================================
server.port=5000
spring.web.error.include-message=always

# Logs
# ===================================================================================
# logging.level.com.immoteam.immoteamdev=DEBUG
# logging.level.org.springframework.security=DEBUG

# JWT
# ===================================================================================
jwt.secret=${JWT_SECRET:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}
jwt.access-token-expiration=604800000
jwt.refresh-token-expiration=604800000

# === CORS pour autoriser les requetes depuis react
# app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173